name: 'walmart_project'
version: '1.0.0'
config-version: 2

profile: 'walmart_project'

model-paths: ["models"]
snapshot-paths: ["snapshots"]

models:
  walmart_project:
    staging:
      +materialized: view
    dimensions:
      +materialized: table
    facts:
      +materialized: table