name: 'sai_dbt_project'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sai_dbt_project:
    silver:
      +database: PC_DBT
      +schema: SILVER
      +materialized: table

    gold:
      +database: PC_DBT
      +schema: GOLD
      +materialized: view

vars:
  wrk_schema: BRONZE
  file_format_json: MY_DB.BRONZE.MY_CSV_FORMAT
  purge_status: FALSE
  stage_name: MY_DB.BRONZE.MY_S3_STAGE
  rawhist_db: MY_DB